language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - memcached

notifications:
  slack:
    secure: KamIqRBK3SsGdoncPoAM1y76Ao9ZSoJubF5HuBAeKdjJWdV+9MeEErZLJ8PLrS86IkfijAVuTSVVQIvHYQm7M7zfqoY9D0Tw9C/2I/C1zAB9qqwMA3og5xb0CcvINpyYWRe7uvPLE5qXvyRleBY2gnasN7b5x2rzVkNFAkT3VF60+hwmL5zHhlphbTMpHOMRpyB1VykMSu8Uba2R7rHE/a7zXQ8jSY2gjlqEKG7mM1U9c1kChwKI+OJoRox3QuAb5W5y3Pu2O4QNapEn0f69L1OkbL1PpkfcFBvsZ5E4hkvP4Yp8ksMRJoBGYtaE+eAB5xJv8kGfsBKKN8HO0CjE7k0VjvommPD/oZdRNkTwGlrBBIvHNNm++nkNxn1HOYUam2yXTPuNZ9HIilWeUsLd9aRL/PxJCTpjaNIR3Y8XM++FNAUzcoPyNaiqM9DqTwdgy1aAmmLO9A262EHMDpAfz2R10NQUVdEk5NeUoaXWEktfPRj2PVHE1dNAos90z8gGA4pstkxRB2dSaGoRYL3vyAieazMix/GlBfnUw9gzz4xNEkfcG8YXC+6qCSdHH97q5DNq/zfsdEKLPgLe/3/mcYaH+e29Q3kgp+GPL5i2iz1v0GPg4K9q0hs841HQCAyE/xBsLpKRSFxc+iCdweVCgF1ZZhy1+INhAelNmowP5E8=

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[34] ]] ; then printf "\nextension=apc.so\n" >> ./tests/travis_php.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION =~ 5.* ]] ; then printf "\nextension=memcache.so\n" >> ./tests/travis_php.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo yes | pecl install apcu-5.1.3; fi;
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add ./tests/travis_php.ini; fi;
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - php -i
  - cat ./tests/travis_php.ini
  
# Setup test run config files
before_script:
  - cat hdconfig.php | sed -e s/your_api_username/$API_USERNAME/ -e s/your_api_secret/$API_SECRET/ -e s/your_api_siteId/$API_SITE_ID/ > hd4CloudConfig.php
  - cat hd4CloudConfig.php > hd4UltimateConfig.php
  - echo "\$hdconfig['use_local'] = true;" >> hd4UltimateConfig.php
  
script: phpunit --debug

after_script:
  - ls -la /tmp
  - ls -la /tmp/hd40store
  - tail -15 hd4CloudConfig.php
  - tail -15 hd4UltimateConfig.php
  
# Note : Having issues with APCu and PHP 7.0    
matrix:
    allow_failures:
        - php: 7.0  